<?php


namespace Sohel\MarkdownParser\Test;


use Illuminate\Foundation\Application;
use Sohel\MarkdownParser\MarkdonwPaserBaseServiceProvider;

class TestCase extends \Orchestra\Testbench\TestCase
{

    protected  function  setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub;
        $this->withFactories(__DIR__.'/../database/factories');
    }

    /**
     * Get package providers.
     *
     * @param Application $app
     *
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [
            MarkdonwPaserBaseServiceProvider::class
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        // Setup default database to use sqlite :memory:
        $app['config']->set('database.default', 'testbench');
        $app['config']->set('database.connections.testbench', [
            'driver'   => 'sqlite',
            'database' => ':memory:',
            'prefix'   => '',
        ]);
    }
}
